# The *pandas* library: Series and DataFrames

Python is a general-purpose scripting language. However, when working in a particular domain, such as the world of data, it can be useful to make use of code libraries that provide higher-level data structures and operations that are suited to that domain.

A library we will be drawing on heavily in this module is *pandas*. If data is represented in an appropriate format, it can make it much easier to work with. *pandas* provides several such formats. In this Notebook, you will learn about two key *pandas* data structures: *Series* and a tabular data structure referred to as a *Dataframe*.

To start with we need to load in the *pandas* library, by convention we associate this with the convenient label *pd*.

In [1]:
import pandas as pd

Note there are several libraries that we shall often make use of when working with *pandas* that have been preloaded in to the Notebook 'for free' [[reference](http://ipython.org/ipython-doc/2/api/generated/IPython.core.magics.pylab.ht
ml)].  However, as a reminder that many libraries we are using are not part of the standard Python code base we will include an `import` statement for the libraries we use.

## Python recap: lists and dicts

Python lists are flexible, mutable, data structures that can be used to represent an ordered list of objects.

In [2]:
simple_list = ['apples', 'oranges', 'bananas', 'pears']

Associated with each list is a numerical *index* value, with a count starting at zero, that identifies the position of each list member. The *N*th list member has index value *N* - 1.

In [3]:
print("First list item (index value 1-1 = 0): simple_list[0] -> {0}".format(simple_list[0]))
print("Third list item (index value 3-1 = 2): simple_list[2] -> {0}".format(simple_list[2]))

First list item (index value 1-1 = 0): simple_list[0] -> apples
Third list item (index value 3-1 = 2): simple_list[2] -> bananas

Python also supports unordered *associative arrays* in the form of *dicts* that allow you to index a value by name:

In [4]:
simple_dict = {1:'one', 2:'two', 4:'four', 3:'three'}
print("Item with key (index) '4' has value: {0}".format(simple_dict[4]))

Item with key (index) '4' has value: four

We can inspect the keys and the values contained within a dict by converting them into a list:

In [5]:
print( list(simple_dict.keys()) )
print( list(simple_dict.values()) )

[1, 2, 4, 3]
['one', 'two', 'four', 'three']

With a simple list or dict, we can use a list or dict comprehension to filter the contents of an object according to a test condition. For example, we can test against the value of the keys in a dict and generate a list containing associated dict values:

In [6]:
[simple_dict[k] for k in simple_dict if k>2]

['four', 'three']

In [7]:
# The following statement makes a new dict by swapping the keys and values
#    contained in simple_dict and prints them out.
alternative_dict = dict(zip(simple_dict.values(), simple_dict.keys()))
print(list(alternative_dict.keys()))
print(list(alternative_dict.values()))

['one', 'two', 'four', 'three']
[1, 2, 4, 3]

## *pandas* Series and DataFrames

In the following sections you will be introduced to two powerful data representations supported by the pandas library: *Series* and *DataFrames*. The introduction provides a quick overview of some of the operations that are possible using these data structures. We will be revisiting many of the operations in more depth later in the module, so for now just try to get a feel for what's possible.

## Series

A *pandas* *Series* combines the idea of a list with an additional index column, by default this is a numeric index starting at zero:

In [8]:
pd.Series( ['one', 'two', 'three', 'four'] )

0      one
1      two
2    three
3     four
dtype: object

We can simplify the text required to create a Series by loading the Series method in from the *pandas* library explicitly:

In [9]:
from pandas import Series
simple_series = Series( [101, 102, 103, 104] )
simple_series

0    101
1    102
2    103
3    104
dtype: int64

We can index into a Series using the corresponding index value:

In [10]:
simple_series[1]

102

We can also grab several values at once if we pass the desired index values in as a list in the order we want them to be displayed:

In [11]:
simple_series[ [1, 0, 3] ]

1    102
0    101
3    104
dtype: int64

In much the same way that we can inspect the keys used in a Python dict, we can inspect the index values used within a Series:

In [12]:
simple_series.index

RangeIndex(start=0, stop=4, step=1)

We can also define our own index values:

In [13]:
myindex_series = Series( ['apple', 'orange', 'pear', 'plum'],
                         index=['one', 'two', 'three', 'four'] )
print(myindex_series.index)
myindex_series

Index(['one', 'two', 'three', 'four'], dtype='object')

one       apple
two      orange
three      pear
four       plum
dtype: object

Again, it's easy enough to pull out several values from the Series by providing several of our own index values in a list:

In [14]:
myindex_series[ ['two', 'four'] ]

two     orange
four      plum
dtype: object

Series can also be created from a simple dict, where the unique key values become index values:

In [15]:
Series( {'Q1':'Spring', 'Q2':'Summer', 'Q3':'Autumn', 'Q4':'Winter'} )

Q1    Spring
Q2    Summer
Q3    Autumn
Q4    Winter
dtype: object

In [16]:
Series({'Q1':'Spring', 'Q2':'Summer', 'Q3':'Autumn', 'Q4':'Winter'},
       index=['Q4', 'Q3', 'Q2', 'Q1'] )

Q4    Winter
Q3    Autumn
Q2    Summer
Q1    Spring
dtype: object

#### Exercise
Construct a Series containing the names of the days of the week and a day number index, ordering the days Monday to Sunday with day index values 1 to 7.   Assign your series to a variable `days_of_the_week`.

In [17]:
# YOUR CODE HERE

##### Sample solution below
But please try to code your own solution before looking at the sample solution provided.

In [18]:
# Sample solution
# first note that simply defining a Series without managing the index starts the indexing at zero.
wrong_index_days_of_the_week = Series( ['Monday', 'Tuesday', 'Wednesday', 'Thursday',
                                 'Friday', 'Saturday', 'Sunday'] )
print(wrong_index_days_of_the_week)

# So we need to supply the index even though it's a simple integer run of values
days_of_the_week = Series( ['Monday', 'Tuesday', 'Wednesday', 'Thursday',
                                 'Friday', 'Saturday', 'Sunday'],
                          index=[1,2,3,4,5,6,7] )
print(days_of_the_week)

0       Monday
1      Tuesday
2    Wednesday
3     Thursday
4       Friday
5     Saturday
6       Sunday
dtype: object
1       Monday
2      Tuesday
3    Wednesday
4     Thursday
5       Friday
6     Saturday
7       Sunday
dtype: object

### 'Vector' operations with Series

In certain respects, we can think of a Series as a vector. For example: if we multiply a Series by a scalar value, each member of the Series is multiplied by that value:

In [19]:
5 * Series([1, 1, 2, 3, 4])

0     5
1     5
2    10
3    15
4    20
dtype: int64

In [20]:
# Similarly with other operations applied to a series.
Series([6, 7, 3, 9, 1]) - 7.1

0   -1.1
1   -0.1
2   -4.1
3    1.9
4   -6.1
dtype: float64

In [21]:
# We can combine two series with simple operations.
Series([1, 1, 2, 3, 4]) + Series([10, 10, 15, -15, -20])
# But be careful if the two series are not the same length - try it and see what happens.

0    11
1    11
2    17
3   -12
4   -16
dtype: int64

### Filtering Series

A very useful feature of Series is that we can filter their values by value. The *values* in the Series (*not* the index values) are tested against the condition and the Series elements that pass the test are returned, along with their index values.

In [22]:
simple_series[ simple_series > 102 ]

2    103
3    104
dtype: int64

This takes a little bit of thinking about. Let's see what the index expression (in the [ ]s) is returning:

In [23]:
simple_series > 102

0    False
1    False
2     True
3     True
dtype: bool

Then, the index values that return `True` are used as the index value to return the Series values associated with them, which in `simple_series` are the values `103` and `104`.

### Aligning data in Series

In many situations it can be useful to be able to add Series elements together where they share some common index values, even if the Series are presented in a different order.

For example, imagine you have two separate Series containing the values of payments made to just the companies who worked on a particular project. Now suppose we want a `totalspend` Series which is the sum of the two Series elements for each company.

In [24]:
# The total spend Series for the four companies starts at zero.
totalSpend = Series({"Company A":0, "Company B":0, "Company C":0, "Company D":0})
totalSpend

Company A    0
Company B    0
Company C    0
Company D    0
dtype: int64

In [25]:
# project1 represents the company expenditures on one project, project2 is another project.
project1 = Series([1000, 2000, 500], index=["Company A", "Company B", "Company C"])
project2 = Series([800, 2000 ], index=["Company D", "Company A"])

What happens if we try adding various combinations of `totalSpend`, `project1` and `project2`, treating them as vectors?

In [26]:
totalSpend + project1

Company A    1000.0
Company B    2000.0
Company C     500.0
Company D       NaN
dtype: float64

In [27]:
project1 + project2

Company A    3000.0
Company B       NaN
Company C       NaN
Company D       NaN
dtype: float64

If any index values don't match across both Series, then the sum for that index value returns *NaN* - not a number. However, using the Series *add* method we can force missing values to be treated as a particular value, such as 0, using a *fill_value* parameter.

In [28]:
totalSpend.add(project1, fill_value=0)

Company A    1000.0
Company B    2000.0
Company C     500.0
Company D       0.0
dtype: float64

The result of the `add()` method is itself a Series.  So, we can also chain the add expressions.

In [29]:
totalSpend.add(project1, fill_value=0).add(project2, fill_value=0)

Company A    3000.0
Company B    2000.0
Company C     500.0
Company D     800.0
dtype: float64

## DataFrames

DataFrames are two-dimensional data tables in which rows of data have values spread across one or more columns, much like a sheet in a spreadsheet. Each column behaves as if it is a Series; a DataFrame can thus be thought of as a dict of Series, where dict keys correspond to column names.

In [30]:
from pandas import DataFrame

In [31]:
# courseData is a dict, with each key the name of a column,
#   and each value a list of the values in that column.
courseData = { 'courseCode': ['TM351', 'TU100', 'M269'],
               'points':[30, 60, 30],
               'level':['3', '1', '2']
             }
print(courseData)

{'courseCode': ['TM351', 'TU100', 'M269'], 'points': [30, 60, 30], 'level': ['3', '1', '2']}

In [32]:
# DataFrame() turns the dict into a DataFrame:
DataFrame(courseData)

  courseCode  points level
0      TM351      30     3
1      TU100      60     1
2       M269      30     2

We can also create a DataFrame from a list of tuples - each tuple becomes a row, and we use `columns` to give a name to the columns:

In [33]:
DataFrame([('a', 1, 2), ('b', 2, 3)], columns=["alpha", 'num1', 'num2'])

  alpha  num1  num2
0     a     1     2
1     b     2     3

We can pull out any required column as a Series by using the column name as a key value...

In [34]:
# ... either with column name as an index value between []s...
course_df = DataFrame(courseData)
course_df['courseCode']

0    TM351
1    TU100
2     M269
Name: courseCode, dtype: object

In [35]:
# ... or as an attribute of the DataFrame:
course_df.courseCode

0    TM351
1    TU100
2     M269
Name: courseCode, dtype: object

To pull out several columns, provide a list of the column names you want to extract as index values:

In [36]:
course_df[ ['courseCode', 'level'] ]

  courseCode level
0      TM351     3
1      TU100     1
2       M269     2

We can force the ordering of columns in the DataFrame by means of the *columns* variable. If a column name is specified that does not have a match in the keys of the source data dict, an 'empty' column is created with all the values set to NaN:

In [37]:
course_df = DataFrame( courseData, columns=['level', 'courseCode', 'title', 'points'])
course_df

  level courseCode title  points
0     3      TM351   NaN      30
1     1      TU100   NaN      60
2     2       M269   NaN      30

We can populate a column with the same value in each cell using a 'scalar' assignment:

In [38]:
course_df.title = 'Unknown'
course_df

  level courseCode    title  points
0     3      TM351  Unknown      30
1     1      TU100  Unknown      60
2     2       M269  Unknown      30

We can also set column values from a Series:

In [39]:
course_df.title = Series(['The data course', 'The foundation course', 'The algorithms course'])
course_df

  level courseCode                  title  points
0     3      TM351        The data course      30
1     1      TU100  The foundation course      60
2     2       M269  The algorithms course      30

We can pull out the values of a column in a similar way:

In [40]:
course_df.title

0          The data course
1    The foundation course
2    The algorithms course
Name: title, dtype: object

One of the reasons for using a library such as *pandas* is that it offers data structures that make working with data as easy as possible.  Sometimes, this requires a little careful thinking about how best to organise the data within a DataFrame.

For example, for the course information DataFrame, it may be most useful to use the course codes as the index values.

In [41]:
course_df = course_df.set_index('courseCode')
course_df

           level                  title  points
courseCode
TM351          3        The data course      30
TU100          1  The foundation course      60
M269           2  The algorithms course      30

The visual presentation of this is slightly misleading - it looks as if there may be a blank row with index value `courseCode`. But the size of the transformed table is correctly shown: one of the columns in the original DataFrame has moved from being a column in its own right to being the index column.

We can pull out one or more rows by referencing the appropriate index element(s) and the columns we wish to extract:

In [43]:
course_df.loc[ ['TU100', 'TM351'], ['title', 'level'] ]

                            title level
courseCode
TU100       The foundation course     1
TM351             The data course     3

If we identify a particular column, we can use an index value to pull out the value from the correspondingly indexed row and the chosen column:

In [44]:
course_df.level['TM351']

'3'

In [45]:
course_df['title']['TM351']

'The data course'

We can also filter the rows of a DataFrame based on the values of one or more columns. We will cover this powerful feature in more depth later in the module.

In [46]:
course_df[course_df.points==30]

           level                  title  points
courseCode
TM351          3        The data course      30
M269           2  The algorithms course      30

You may recall that passing a column name in as the DataFrame key returns a Series containing the values of the column:

In [47]:
course_df['title']

courseCode
TM351          The data course
TU100    The foundation course
M269     The algorithms course
Name: title, dtype: object

Paraphrasing the author of pandas, Wes McKinney, writing in his book _Python for Data Analysis_, '[this apparent inconsistency] in syntax arose out of practicality and nothing more'. Pragmatic programming, as you might, FTW! (FTW is slang for 'for the win', a positive exclamation in gamer culture.)

#### Unique items in a column

We can pull out the unique values contained within a column very easily by applying the `unique()` function to the appropriate column:

In [48]:
course_df['points'].unique()

array([30, 60])

We can easily iterate through the items:

In [49]:
for item in course_df['points'].unique():
    print(item)

30
60

To get a list rather than an array, make use of the `tolist()` helper function:

In [50]:
course_df['points'].unique().tolist()

[30, 60]

#### Column typing in DataFrames

In order to perform certain operations on a column, the column needs to be correctly typed - that is, all elements need to be of a particular type.

You can check the type of each column in a DataFrame using the `.dtypes` attribute:

In [51]:
course_df.dtypes

level     object
title     object
points     int64
dtype: object

Here we see that the `level` and `title` are classed as object types, but the `points` values have been identified as integers.

## Further information

*pandas'* Series and DataFrame objects provide several more useful, and powerful, data-manipulation methods than have been described here. You will meet many of them later in the module, as and when they are required.  Ifyou want to read some more about these core *pandas'* data structures you can find some additional information at [*pandas*: Intro to Data Structures](http://pandas.pydata.org/pandas-docs/stable/dsintro.html)

If you would like to learn about *pandas* in more depth, a copy of the book written by pandas' original developer, Wes McKinney, is available as an ebook via the OU Library: [Python for Data Analysis](http://proquestcombo.safaribooksonline.com.libezproxy.open.ac.uk/book/programming/python/9781449323592)

## What next?

Having hopefully got to grips with the *pandas'* very powerful tabular DataFrame representation, you now need to start filling them with data.

If you are working through this Notebook as part of an inline exercise, return to the module materials now.

If you are working through this set of Notebooks as a whole, move to the Notebook `02.2 Data file formats` to learn how to open files and parse their data contents into a *pandas* DataFrame.